name: projetA62
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          #GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          GDRIVE_CREDENTIALS_DATA: '{"access_token": "ya29.a0ARrdaM8zMXhrq8TgWbj2wyJuNG1HhrLgZm_PSyeycUcLas3iCFcA7wLqcat8SEX2oJh_qm7suUueEulxBZznxHvtM7nXVO_avIiH6nu5LIUECFWThxm5IHL9Qc9OYif5_u5cL01NuOIwiNuEX6e_qvfkVjxN", "client_id": "710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com", "client_secret": "a1Fz59uTpVNeG_VGuSKDLJXv", "refresh_token": "1//04XfZoFXl1bBrCgYIARAAGAQSNwF-L9Ir273eun1GqHZl6gX_ygZDJ2Wi4aRfUAi60tjmOW1A4bbb7BoiJXONKupvSCUQncO2H8s", "token_expiry": "2021-12-31T02:15:31Z", "token_uri": "https://oauth2.googleapis.com/token", "user_agent": null, "revoke_uri": "https://oauth2.googleapis.com/revoke", "id_token": null, "id_token_jwt": null, "token_response": {"access_token": "ya29.a0ARrdaM8zMXhrq8TgWbj2wyJuNG1HhrLgZm_PSyeycUcLas3iCFcA7wLqcat8SEX2oJh_qm7suUueEulxBZznxHvtM7nXVO_avIiH6nu5LIUECFWThxm5IHL9Qc9OYif5_u5cL01NuOIwiNuEX6e_qvfkVjxN", "expires_in": 3599, "scope": "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.appdata", "token_type": "Bearer"}, "scopes": ["https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/drive.appdata"], "token_info_uri": "https://oauth2.googleapis.com/tokeninfo", "invalid": false, "_class": "OAuth2Credentials", "_module": "oauth2client.client"}'

        run: |
          
          echo "chargement des donnees"
          dvc pull model
          echo "chargement termine"

          pip install -r requirements.txt
          jupyter nbconvert --to notebook --execute notebook/iteration_9_1_test_model_sur_git.ipynb
          
          echo "FINI"

          
          # Your ML workflow goes here
          #pip install -r requirements.txt
          #python Pointure_GaussianNB.ipynb
          #jupyter nbconvert --to notebook --execute Pointure_GaussianNB.ipynb
          # Write your CML report
          #echo "## Metriques:" >> report.md
          #cat metrics.txt >> report.md