name: projetA62
on:
  push:
    branches:
      - main
      - CML_plus_dvc 
jobs:
  CI_generate_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      
      - name: intstall_requirements
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          
          
      - name: upload data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull model
          ls -lrt model/

          jupyter nbconvert --to notebook --execute notebook/iteration_4_generate_model_cnn.ipynb

          pip freeze > requirements_docker.txt
          python --version > python_version.txt

      - name: preparer_gitpush
        run: |
          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git add requirements_docker.txt python_version.txt report.md
          
          echo $(date +%Z)
          git commit --allow-empty -m "push requirements at $(date +%d-%b-%H_%M)"
          
          #git tag -a "v2.2" -m "tag avec temoin.txt depuis gitactions"
          #git push --follow-tags
          #git push --tags
          git push
        env:
          GITHUB_USERNAME: "$GITHUB_USERNAME"
          GITHUB_EMAIL: "$GITHUB_EMAIL"





          
                    
        